#CDIA:::Introduction to AI - Basic Python Programming

Ibai Laña

#BASIC STRUCTURES

In [2]:
a = 42
a

42

In [3]:
a+=3
a

45

## Lists, arrays and matrices

In [4]:
a = [2]
b = [1,2,3,4]

print (a)
print (b)

[2]
[1, 2, 3, 4]


In [5]:
### add elements
a.append(3)
b.append(5)
print (a)
print (b)


[2, 3]
[1, 2, 3, 4, 5]


In [6]:
### get elements
b[2]

3

In [7]:
### get size
len (b)

5

In [8]:
### bi dimensional lists-->a  2x3 matrix
a = [[1,3], [3,4], [5,6]]
print ("1-", a)
print ("2-",len (a))
print ("3-",a[1])
print ("4-",a[:2])
print ("5-",a[-1])
print ("6-",a[0:1])
print ("7-",len (a[1]))
###get individual element
print ("8-",a[1][0])

1- [[1, 3], [3, 4], [5, 6]]
2- 3
3- [3, 4]
4- [[1, 3], [3, 4]]
5- [5, 6]
6- [[1, 3]]
7- 2
8- 3


In [9]:
### lists are very comfortable but..
c = [[2,3,4], [2,3], "1", ["H", "N"]]
### you can list pretty much everything

### differences with Numpy ARRAYS
It is very similar but we have structure and plenty of operations over arrays. If we need some of these operations it might be better to work with arrays. Normally it is easier to operate with lists, and when needed, cast them to arrays.

In [10]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
a.shape


(3,)

Second array is not bidimensional, instead, the array casting instruction has converted it to an array of one dimension of lists (and objects). 
Operating with arrays can be as transparent as with lists, the get [] works the same, and the len also. But we have "shape" and many other functions:

In [15]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (ar2[1])
#flatten the array:
print (ar2.ravel())
#get the diagonal of a square matrix:
print (ar2.diagonal())
#delete elements:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ar3 = np.delete(ar2, 0) #beware, this deletes the first element of the first element
print (ar3)
#if the element to delete is the first or last, it's easier to just reassign 
#a different subarray:
ar4 = ar2[1:]#-->removes the first, assigning from the 2nd onwards. 
print (ar4)

[4 5 6]
[1 2 3 4 5 6 7 8 9]
[1 5 9]
[2 3 4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]


## FIFO QUEUE
List for which we can append new elements and remove others

In [16]:
fifo = []
#adding: 
fifo.append(1)
fifo.append(2)
fifo.append (3)
print (fifo)


[1, 2, 3]


In [17]:
#removing
def pop_from_fifo(fifo):
  element=fifo[0]
  fifo=fifo[1:]
  return element, fifo

popped, fifo = pop_from_fifo(fifo)
print (popped)
print (fifo)

1
[2, 3]


## LIFO STACK
very similar to fifo but removing and deleting from the end

In [18]:
lifo = []
#adding: 
lifo.append(1)
lifo.append(2)
lifo.append (3)
print (lifo)

[1, 2, 3]


In [19]:
def pop_from_lifo(lifo):
  element=lifo[-1]#-->we get the last element
  lifo=lifo[:-1]#-->we consider all elements except the last
  return element, lifo

popped, lifo = pop_from_lifo(lifo)
print (popped)
print (lifo)

3
[1, 2]


## DICTIONARIES
Structures to have pairs of elements key and value. Similar to a json element

In [20]:
a = {"B":[1,2,3], "C":"A TEXT VALUE"}
print (a["B"])
print (a["C"])

#new elements by just creating new keys:
a["D"]=[4,5,6]
print (a)

#check keys and values (they are arrays, so they can be iterated)
print (a.keys())
print (a.values())

for value in a.values():
  print ("-->", value)

[1, 2, 3]
A TEXT VALUE
{'B': [1, 2, 3], 'C': 'A TEXT VALUE', 'D': [4, 5, 6]}
dict_keys(['B', 'C', 'D'])
dict_values([[1, 2, 3], 'A TEXT VALUE', [4, 5, 6]])
--> [1, 2, 3]
--> A TEXT VALUE
--> [4, 5, 6]


# DATAFRAMES
an optimal way to deal with memory structures which is also specially suited to read and write to different text formats (csv, json, txt...)


In [21]:
import pandas as pd
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [22]:
df["COLUMN 1"]=[1,2,3,4,5]
df["COLUMN 2"]=[6,7,8,99,0]
df

COLUMN 1  COLUMN 2
0         1         6
1         2         7
2         3         8
3         4        99
4         5         0

In [23]:
df["COLUMN 1"]


0    1
1    2
2    3
3    4
4    5
Name: COLUMN 1, dtype: int64

In [24]:
df["COLUMN 1"].values

array([1, 2, 3, 4, 5])

In [28]:
df = pd.read_csv("sample_data/california_housing_train.csv")
df

longitude  latitude  housingMedianAge  totalRooms  totalBedrooms  \
0        -114.31     34.19                15        5612           1283   
1        -114.47     34.40                19        7650           1901   
2        -114.56     33.69                17         720            174   
3        -114.57     33.64                14        1501            337   
4        -114.57     33.57                20        1454            326   
...          ...       ...               ...         ...            ...   
16995    -124.26     40.58                52        2217            394   
16996    -124.27     40.69                36        2349            528   
16997    -124.30     41.84                17        2677            531   
16998    -124.30     41.80                19        2672            552   
16999    -124.35     40.54                52        1820            300   

       population  households  medianIncome  medianHouseValue  
0            1015         472        1.4936             66900  
1            1129         463        1.8200             80100  
2             333         117        1.6509             85700  
3             515         226        3.1917             73400  
4             624         262        1.9250             65500  
...           ...         ...           ...               ...  
16995         907         369        2.3571            111400  
16996        1194         465        2.5179             79000  
16997        1244         456        3.0313            103600  
16998        1298         478        1.9797             85800  
16999         806         270        3.0147             94600  

[17000 rows x 9 columns]