<span style="font-family:Calibri">

# 🧬 **Genetic Algorithms**

### *Introduction to Artificial Intelligence*  
*2024/2025*

**Universidad de Deusto**  
*Valle Varo*

---
## 📖 **Introduction**
A **Genetic Algorithm (GA)** is an optimization technique inspired by the process of natural selection 🌱. It mimics biological evolution to find solutions to optimization and search problems. By evolving a population of solutions through selection, crossover, and mutation, GAs are particularly effective in complex problem spaces where traditional methods might struggle.

---

## 🧠 **Key Concepts**

1. **Population** 👥: A collection of potential solutions to the problem, each called a "chromosome" or "individual."
2. **Chromosome** 🧬: Represents a possible solution. It's usually encoded as a string (often binary) that defines the characteristics of the solution.
3. **Fitness Function** 💪: A function that evaluates and scores each chromosome based on how well it solves the problem.
4. **Selection** 🎯: The process of choosing the fittest individuals to pass their genes to the next generation.
5. **Crossover** 🔗: A genetic operator that combines two parent chromosomes to produce offspring. It mimics reproduction and the inheritance of traits.
6. **Mutation** ⚡: A genetic operator that introduces small random changes to individual chromosomes to maintain diversity and prevent premature convergence.
7. **Evolution** 🔄: The iterative process where the population is evolved over multiple generations to improve the overall fitness.

---

## 🧬 **Steps in a Genetic Algorithm**

1. **Initialization** 🌱:
   - Begin with a randomly generated population of individuals (chromosomes).
   
2. **Fitness Evaluation** 📊:
   - Evaluate each individual in the population using the **fitness function** to measure how good it is at solving the problem.

3. **Selection** 🎯:
   - Select individuals based on their fitness scores. Fitter individuals have a higher chance of being chosen for reproduction, mimicking the concept of "survival of the fittest."

4. **Crossover (Recombination)** 🔗:
   - For each pair of selected parents, combine their genetic material to create new offspring. This is often done by swapping portions of their chromosome strings.

5. **Mutation** ⚡:
   - Apply small random changes to some offspring to maintain diversity in the population and avoid getting stuck in local optima.

6. **Replacement** 🔄:
   - Replace some or all of the old population with the new offspring, creating the next generation.

7. **Termination** 🏁:
   - Repeat the process of evaluation, selection, crossover, and mutation until a termination condition is met, such as a maximum number of generations or convergence to a solution.

---

## 📝 **Pseudocode for Genetic Algorithm**

```plaintext
1. Initialize a population of random solutions.
2. Evaluate the fitness of each individual in the population.
3. Repeat until termination condition is met:
   a. Select individuals to reproduce based on their fitness.
   b. Apply crossover to generate new offspring.
   c. Apply mutation to offspring.
   d. Evaluate the fitness of the new individuals.
   e. Replace the old population with the new one.
4. Return the best solution found.


---

**Initialisation**

In [4]:
import numpy as np
np.random.seed(100)

**Fitness Function**

In [5]:
#Calculate fitness of population

def calculate_fitness(inputs, population):
    
    '''
    Description: This function calculates the fitness of our solutions
    
    Input Arguments: input values and a population of weights
    
    Output: Fitness - a fitness value
    
    '''
    
    fitness = np.sum(population*inputs, axis=1)
    return fitness

Next, we proceed to choose parents that will mate. This involves choosing the most fit parents in the population according to our fitness value.

**Selection of the fittest**

In [6]:
#Choose parents to mate
def choose_mating(population, fitness, number_of_parents):
    
    '''
    Description: This function chooses the most fit solutions to mate in order to yield the next generation
    
    Input Arguments: a population, the fitness and the number of parents required to mate
    
    Output: 
    
    the parents to mate
    '''
    
    #initialize empty numpy array to hold parents
    parents = np.empty((number_of_parents, population.shape[1]))
    
    #loop to fill the created parents array with the fittest solutions and stop at the required number of parents
    for number in range(number_of_parents):
        maximum_fitness_index = np.where(fitness == np.max(fitness))
        maximum_fitness_index = maximum_fitness_index[0][0]
        parents[number, :] = population[maximum_fitness_index, :]
        # This line modifies the fitness array by setting the fitness value of the currently 
        # selected "fittest" individual to a very large negative number, so that in subsequent iterations of the loop 
        # it will not be selected. 
        fitness[maximum_fitness_index] = -99999999999
        
    return parents

**Crossing over**

In [7]:
#Perform cross over

def crossingover(parents, size_of_offspring):
    '''
    Description: This function performs a one point cross over operation on the parents. 
    
    Input Arguments:
    Parents - the parents pool to be crossed over
    size of offspring - the size of offspring required
    
    Output: 
    
    offspring - the crossed over offspring
    '''
    # initialize an empty numpy array to hold the offsprings
    offspring = np.empty(size_of_offspring)
    
    # specify the point of cross over - at the center in our case
    point_of_crossover = np.uint8(size_of_offspring[1]/2)
    
    #loop over the number of offspring required to get the required offsprings
    
    for k in range(size_of_offspring[0]):
        # get index of first parent to be mated
        parent1_index = k%parents.shape[0]
        # get index of second parent to be mated
        parent2_index = (k+1)%parents.shape[0]
        # proceed to assign the first half of the first parents gene to the first half gene of the offspring
        offspring[k, 0:point_of_crossover] = parents[parent1_index, 0:point_of_crossover]
        # proceed to assign the second half of the second parents gene to the second half gene of the offspring
        offspring[k, point_of_crossover:] = parents[parent2_index, point_of_crossover:]
        
    return offspring

**Mutation**

In [8]:
#perform mutation

def mutation(cross_over_offspring):
    
    '''
    Description: This function performs some random variation to the genes of the 
    solutions by adding a random bias number.
    
    Input - 
    cross_over_offspring - offspring obtained from the cross over function
    
    Output -
    Mutated offspring 
    
    '''
    
    #loop over the offsprings and add a random bias number to their genes
    for number in range(cross_over_offspring.shape[0]):
        # Create the random bias number to be used for muation. The arguments taken are the limits(low and high) and the size
        random_bias_number = np.random.uniform(-1.5, 1.5, 1)
        
        #Proceed to mutate by adding the bias number
        
        cross_over_offspring[number, 3] = cross_over_offspring[number, 3] + random_bias_number
    return cross_over_offspring

<span style="font-family:Calibri">

## 🚀 **Implementing the Genetic Algorithm**

In this section, we will apply the genetic algorithm to a simple example function with the goal of maximizing it. 

The function we will be working with is defined as:

> $$ F(X) = A_1X_1 + A_2X_2 + A_3X_3 + A_4X_4 $$

where the variables are initialized as follows:
- $ X_1 = 4 $
- $ X_2 = -2 $
- $ X_3 = 3.5 $
- $ X_4 = -4.2 $

These values are chosen randomly.

Our objective is to optimize the coefficients $A_1, A_2, A_3, A_4$ to maximize the function  $F(X)$.

To achieve this, we will start with a set of input values for $X$ and then define the number of weights. Next, we will specify the number of generations through which the mating process will occur. At the end of the specified generations, we will select the best solutions.

The previously defined functions will be combined to form the genetic algorithm, allowing us to explore the search space effectively and yield the maximum value for the function over the designated generations.


In [12]:
'''
Implementing the GA

'''
# Specify inputs of the equation ( X values)
inputs = [4,-2,3.5,-4.2]

# Specify the number of weights or multipliers (A values, in our case) for each input which we are looking to optimize
number_of_weights = 4

# Specify the number of solutions in each generation. Each solution will have the number of weights
solutions = 6

#Specify the number of parents mating to yield the specified number of solutions
number_of_parents_mating = 2

# Define the population size based on the number of parents mating and the number of solutions
population_size = (solutions,number_of_weights)

#randomly create the inital population according to the specified population size
new_population = np.random.uniform(low=-5.0, high=5.0, size=population_size)

#Print out the initialized population
print(new_population)


#Specify the number of generations to mutate through 
number_of_generations = 30

#Loop over the specified number of generations

for generation in range(number_of_generations):
    
    #Print the generation in which we are currently looping through to keep track
    print("Generation : ", generation)
    
    # Calculate the fitness of the population in the current generation
    fitness = calculate_fitness(inputs, new_population)

    # Proceed to select the most fit parents to mate
    parents = choose_mating(new_population, fitness, 
                                      number_of_parents_mating)

    # Proceed to create offsprings via the one point cross over
    crossover = crossingover(parents,
                                       size_of_offspring=(population_size[0]-parents.shape[0], number_of_weights))

    # Proceed to add random bias to the genes of the created offspring via the mutation function
    mutated = mutation(crossover)

    # Proceed to create the new population from the parents and the mutated
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = mutated

    # Get the best or most fit solution in this current generation
    print("Best result : ", np.max(np.sum(new_population*inputs, axis=1)))



[[ 3.60394191  4.19755359  3.49607326 -2.45533465]
 [ 3.77555542 -0.6486981   2.29494344 -0.87359232]
 [-3.09163954  2.0601952  -2.59367179  3.51324427]
 [ 3.24102289  0.25211787 -1.13659206  0.90880791]
 [-3.62476385  3.08270408  4.65825815  2.79795804]
 [-2.60664918  3.67260413  3.08115013 -4.36318876]]
Generation :  0
Best result :  37.818243146759144
Generation :  1
Best result :  43.5320008341658
Generation :  2
Best result :  43.5320008341658
Generation :  3
Best result :  48.70324359716897
Generation :  4
Best result :  48.75588657478272
Generation :  5
Best result :  54.36644762355026
Generation :  6
Best result :  58.49483305068624
Generation :  7
Best result :  62.98880106135685
Generation :  8
Best result :  69.1297155988526
Generation :  9
Best result :  70.79724090444314
Generation :  10
Best result :  75.92897057808801
Generation :  11
Best result :  81.082985871357
Generation :  12
Best result :  82.34783437808298
Generation :  13
Best result :  86.5177317375781
Generati

C:\Users\m.varo\AppData\Local\Temp\ipykernel_23828\921913505.py:24: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  cross_over_offspring[number, 3] = cross_over_offspring[number, 3] + random_bias_number


## 📚 **References for Genetic Algorithms**

1. **Holland, J. H.** (1975). *Adaptation in Natural and Artificial Systems*. University of Michigan Press.  
   - A foundational text on genetic algorithms and their applications in optimization problems.

2. **Goldberg, D. E.** (1989). *Genetic Algorithms in Search, Optimization, and Machine Learning*. Addison-Wesley.  
   - This book provides comprehensive insights into genetic algorithms, including theory and practical applications.

3. **Mitchell, M.** (1996). *An Introduction to Genetic Algorithms*. MIT Press.  
   - An accessible introduction to genetic algorithms, covering both theory and real-world applications.

4. **Fogel, D. B.** (2000). *Evolutionary Computation: A Unified Approach*. IEEE Press.  
   - This work explores various evolutionary computation techniques, including genetic algorithms, in a unified framework.

5. **Bäck, T., Fogel, D. B., & Michalewicz, Z.** (1997). *Handbook of Evolutionary Computation*. Oxford University Press.  
   - A comprehensive reference that covers a wide range of topics in evolutionary computation, including genetic algorithms, with contributions from multiple authors.


---