#CDIA:::Introduction to AI - Basic Python Programming

Ibai Laña

#BASIC STRUCTURES

In [1]:
a = 42
a

42

In [2]:
a= a+3
a

45

## Lists, arrays and matrices

In [ ]:
a = [2]
b = [1,2,3,4]

print (a)
print (b)

[2]
[1, 2, 3, 4]


In [ ]:
### add elements
a.append(3)
b.append(5)
print (a)
print (b)


[2, 3]
[1, 2, 3, 4, 5]


In [ ]:
### get elements
b[2]

3

In [ ]:
### get size
len (b)

5

In [3]:
### bi dimensional lists-->a  2x3 matrix
a = [[1,3], [3,4], [5,6]]
print ("1-", a)
print ("2-",len (a))
print ("3-",a[1])
print ("4-",a[:2])
print ("5-",a[-1])
print ("6-",a[0:1])
print ("7-",len (a[1]))
###get individual element
print ("8-",a[1][0])

1- [[1, 3], [3, 4], [5, 6]]
2- 3
3- [3, 4]
4- [[1, 3], [3, 4]]
5- [5, 6]
6- [[1, 3]]
7- 2
8- 3


In [ ]:
### lists are very comfortable but..
c = [[2,3,4], [2,3], "1", ["H", "N"]]
### you can list pretty much everything

### Difference with Numpy ARRAYS
It is very similar but we have structure and plenty of operations over arrays. If we need some of these operations it might be better to work with arrays. Normally it is easier to operate with lists, and when needed, cast them to arrays.

In [5]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.shape


(3,)

In [6]:
a  =[[1,2],[2,3],[3,3]]
c = [[2,3,4], [2,3], "1", ["H", "N"]]

ar= np.array(a)
ar2 = np.array(c)

<ipython-input-6-d1427536fef7>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array(c)


In [ ]:
print (ar)
print (ar.shape)
print (ar2)
print (ar2.shape)

[[1 2]
 [2 3]
 [3 3]]
(3, 2)
[list([2, 3, 4]) list([2, 3]) '1' list(['H', 'N'])]
(4,)


Second array is not bidimensional, instead, the array casting instruction has converted it to an array of one dimension of lists (and objects).
Operating with arrays can be as transparent as with lists, the get [] works the same, and the len also. But we have "shape" and many other functions:

In [ ]:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (ar2[1])
#flatten the array:
print (ar2.ravel())
#get the diagonal of a square matrix:
print (ar2.diagonal())
#delete elements:
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ar3 = np.delete(ar2, 0) #beware, this deletes the first element of the first element
print (ar3)
#if the element to delete is the first or last, it's easier to just reassign
#a different subarray:
ar4 = ar2[1:]#-->removes the first, assigning from the 2nd onwards.
print (ar4)

[4 5 6]
[1 2 3 4 5 6 7 8 9]
[1 5 9]
[2 3 4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]


## FIFO QUEUE
List for which we can append new elements and remove others

In [7]:
fifo = []
#adding:
fifo.append(1)
fifo.append(2)
fifo.append (3)
print (fifo)


[1, 2, 3]


In [ ]:
#removing
def pop_from_fifo(fifo):
  element=fifo[0]
  fifo=fifo[1:]
  return element, fifo

popped, fifo = pop_from_fifo(fifo)
print (popped)
print (fifo)

1
[2, 3]


## LIFO STACK
very similar to fifo but removing and deleting from the end

In [ ]:
lifo = []
#adding:
lifo.append(1)
lifo.append(2)
lifo.append (3)
print (lifo)

[1, 2, 3]


In [ ]:
def pop_from_lifo(lifo):
  element=lifo[-1]#-->we get the last element
  lifo=lifo[:-1]#-->we consider all elements except the last
  return element, lifo

popped, lifo = pop_from_lifo(lifo)
print (popped)
print (lifo)

3
[1, 2]


## DICTIONARIES
Structures to have pairs of elements key and value. Similar to a json element

In [10]:
a = {"B":[1,2,3], "C":"A TEXT VALUE"}
print (a["B"])
print (a["C"])

#new elements by just creating new keys:
a["D"]=[4,5,6]
print (a)

#check keys and values (they are arrays, so they can be iterated)
print (a.keys())
print (a.values())

for value, key in zip(a.values(),a.keys()):
  print (key+"-->"+ str(value))

[1, 2, 3]
A TEXT VALUE
{'B': [1, 2, 3], 'C': 'A TEXT VALUE', 'D': [4, 5, 6]}
dict_keys(['B', 'C', 'D'])
dict_values([[1, 2, 3], 'A TEXT VALUE', [4, 5, 6]])
B-->[1, 2, 3]
C-->A TEXT VALUE
D-->[4, 5, 6]


# DATAFRAMES
an optimal way to deal with memory structures which is also specially suited to read and write to different text formats (csv, json, txt...)


In [11]:
import pandas as pd
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
df["COLUMN 1"]=[1,2,3,4,5]
df["COLUMN 2"]=[6,7,8,99,0]
df

COLUMN 1  COLUMN 2
0         1         6
1         2         7
2         3         8
3         4        99
4         5         0

In [ ]:
df["COLUMN 1"]


0    1
1    2
2    3
3    4
4    5
Name: COLUMN 1, dtype: int64

In [ ]:
df["COLUMN 1"].values

array([1, 2, 3, 4, 5])

In [ ]:
df = pd.read_csv("sample_data/california_housing_train.csv")
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]